services:
    pgvector:
        image: pgvector/pgvector:0.8.6-pg18-trixie
        container_name: pgvector
        ports:
            - "5433:5432"
        volumes:
            - pgvector_data:/var/lib/postgresql
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        networks:
            - backend
        restart: always

networks:
    backend:

volumes:
    pgvector_data:
