APP_NAME="Retriever"
APP_VERSION="0.1.0"

FILE_ALLOWED_TYPES=["text/plain", "application/pdf"]
FILE_ALLOWED_SIZES_MB=10
FILE_DEFAULT_CHUNK_SIZE=512000

POSTGRES_USERNAME="postgres"
POSTGRES_PASSWORD="password123"
POSTGRES_HOST="pgvector"
POSTGRES_PORT="5432"
POSTGRES_MAIN_DATABASE="Retriever"

# ============================= LLM Config =============================

GENERATION_BACKEND = "OPENAI"
EMBEDDING_BACKEND = "COHERE"

OPENAI_API_KEY=""
OPENAI_API_URL=""
COHERE_API_KEY=""

GENERATION_MODEL_ID=""
EMBEDDING_MODEL_ID=""
EMBEDDING_MODEL_SIZE=

INPUT_DEFAULT_MAX_CHARACTERS=1024
GENERATION_DEFAULT_MAX_TOKENS=1024
GENERATION_DEFAULT_TEMP=0.1

# ============================= VectorDB Config =============================

VECTOR_DB_BACKEND_LITERAL = ["PGVECTOR", "QDRANT"]
VECTOR_DB_BACKEND = "PGVECTOR"
VECTOR_DB_PATH = "qdrant_db"
VECTOR_DB_DISTANCE_METHOD_LITERAL = ["cosine", "dot"]
VECTOR_DB_DISTANCE_METHOD = "cosine"
VECTOR_DB_PGVC_INDEX_THRESHOLD =

# ========================= Template Config =============================

PRIMARY_LANGUAGE = "en"
DEFAULT_LANGUAGE = "en"